apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: delveserver
  namespace: default
  labels:
    app: delveserver
spec:
  selector:
    matchLabels:
      name: delveserver
  template:
    metadata:
      labels:
        name: delveserver
    spec:
      hostNetwork: true
      hostIPC: true
      hostPID: true
      containers:
      - name: delveserver
        image: delveserver
        imagePullPolicy: Never
        ports:
        - containerPort: 3333
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_PTRACE
        volumeMounts:
          - name: socket-path
            mountPath: /var/run/docker.sock
            # mountPath: /run/containerd/containerd.sock，如果使用containerd的话
          - name: sys-path
            mountPath: /sys
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "100Mi"
      - name: delveclient
        image: delveclient
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
      terminationGracePeriodSeconds: 30

      volumes:
        - name: socket-path
          hostPath:
            path: /var/run/docker.sock
        - name: sys-path
          hostPath:
            path: /sys



