apiVersion: v1
kind: Service
metadata:
    name: delveserverservice
    labels:
        name: delveserverservice
spec:
    type: NodePort
    selector:
        app: delveserver
    ports:
        - protocol: TCP
          nodePort: 30003
          port: 3333
          targetPort: 3333